Repository nicholas-fedor/watchtower, pull requests merged in 2025-04, with the labels that each got.

#163 fix(network): exclude Aliases and DNSNames on default bridge network
  go.mod
  go.sum
  pkg/container/container_source.go
Labels: type/minor

#185 feat(digest): enhance HEAD request compatibility with OCI indexes
  go.mod
  go.sum
  pkg/container/image.go
  pkg/registry/digest/digest.go
  pkg/registry/helpers/helpers.go
  pkg/registry/registry.go
  pkg/registry/trust.go
  pkg/registry/trust_test.go
Labels: type/patch

#205 Optional tag filter
  README.md
  docs/arguments.md
  docs/http-api-mode.md
  pkg/filters/filters.go
  pkg/filters/filters_test.go
  pkg/notifications/notifier_test.go
Labels: enhancement, type/minor

#237 fix: enhance MAC address handling for host network mode in container recreation
  go.mod
  go.sum
  pkg/container/client.go
  pkg/container/container_mock_test.go
  pkg/container/container_source.go
  pkg/container/container_target.go
  pkg/container/container_test.go
  pkg/container/errors.go
Labels: type/patch
